### ISSUE TITLE
Unfortunately no longer works under 21.1

### ISSUE THREAD

**Issue by joehoub** [foex-open-source/fos-splitter#3]
if I install your demo app under 21.1 and update the universal theme, the splitter plugin no longer works

**Comment by mnolan866** [comment]
This is due to some changes in the universal theme i.e. HTML structure of child regions, class name changes etc.

We will be releasing a new version of all the plug-ins that support APEX 21.1 in the near future. This will include a fix for this issue. 

FYI: we provide immediate resolution of issues for customers that have purchased [extra support](https://www.foex.at/fos/#support) for FOS plug-ins.

**Comment by foex-open-source** [comment]
Fixed in just published v21.1.0
